# -*- coding: utf-8 -*-
"""Quandl Historical Crypto Prices

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l2oFInpj6He3M5PjZLbTPI16ehxQieCI

Download data from Quandl. The data set constituents:

Bitcoin
Ethereum
Gold
Eurekahedge Crypto Hedge Fund Index
"""

###############################################################################
#                          1. Import Libraries                             #
###############################################################################
!pip install quandl
import quandl
import datetime
import pandas as pd
from pandas_datareader import data as pdr
from google.colab import  drive
drive.mount("/drive", force_remount=True)
quandl.ApiConfig.api_key ="8T_MwCyyd93FZLysnMrX"
###############################################################################
#                               2. Read data                                  #
###############################################################################
# Set label

crypto_fund_index = quandl.get("EUREKA/682", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2013-07-31", end_date="2020-07-31")
oil = quandl.get("FRED/DCOILBRENTEU", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")
gold = quandl.get("LBMA/GOLD", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")
btc_usd = quandl.get("BITFINEX/BTCUSD", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")
eth_btc = quandl.get("BITFINEX/ETHBTC", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")
eth_usd = quandl.get("BITFINEX/ETHUSD", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")
zcash_btc = quandl.get("BITFINEX/ZECBTC", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")
zcash_usd = quandl.get("BITFINEX/ZECUSD", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")
btc_wallets = quandl.get("BCHAIN/MWNUS", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")
btc_tx_val = quandl.get("BCHAIN/MWNTD", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")
btc_tx_vol = quandl.get("BCHAIN/ETRAV", authtoken="8T_MwCyyd93FZLysnMrX", start_date="2020-01-01", end_date="2020-08-01")

###############################################################################
#                               3. Export data                                  #
###############################################################################

# Grab data
crypto_fund_index.to_csv("/drive/My Drive/Python/financial_data/quandl/cryptofund_historical_returns.csv", sep = ',')
oil.to_csv("/drive/My Drive/Python/financial_data/quandl/oil_historical_prices.csv", sep = ',')
gold.to_csv("/drive/My Drive/Python/financial_data/quandl/gold_historical_prices.csv", sep = ',')
btc_usd.to_csv("/drive/My Drive/Python/financial_data/quandl/btc_usd_historical_prices.csv", sep = ',')
eth_btc.to_csv("/drive/My Drive/Python/financial_data/quandl/eth_btc_historical_prices.csv", sep = ',')
eth_usd.to_csv("/drive/My Drive/Python/financial_data/quandl/eth_usd_historical_prices.csv", sep = ',')
zcash_btc.to_csv("/drive/My Drive/Python/financial_data/quandl/zcash_btc_historical_prices.csv", sep = ',')
zcash_usd.to_csv("/drive/My Drive/Python/financial_data/quandl/zcash_usd_historical_prices.csv", sep = ',')
btc_wallets.to_csv("/drive/My Drive/Python/financial_data/quandl/btc_wallets.csv", sep = ',')
btc_tx_val.to_csv("/drive/My Drive/Python/financial_data/quandl/btc_tx_val.csv", sep = ',')
btc_tx_vol.to_csv("/drive/My Drive/Python/financial_data/quandl/btc_tx_vol.csv", sep = ',')